name: Lightning Timeseries

on:
  workflow_dispatch:

permissions:
  contents: write  # Grant the necessary permission to write to the repository

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install boto3
        pip install botocore
        pip install Python-IO
        pip install pandas
        pip install matplotlib
        pip install pyftpdlib
        pip install cartopy
        pip install datetime
        pip install netCDF4
        pip install os-sys
    

    - name: Run lightning_timeseries script
      run: 
        python lightning_timeseries.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add figure.png
        git commit -m "Add plot"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
