name: Lightning Timeseries

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Grant the necessary permission to write to the repository

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install boto3
        pip install botocore
        pip install Python-IO
        pip install pandas
        pip install matplotlib
        pip install pyftpdlib
        pip install cartopy
        pip install datetime
        pip install netCDF4
        pip install scipy
    

    - name: Run lightning_timeseries script
      run: 
        python lightning_timeseries.py

    - name: Handle changes and push updates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Stash any local changes
        git stash
        
        # Pull the latest changes
        git pull --rebase origin main || true
        
        # Apply stashed changes
        git stash pop || true
        
        # Add changes to commit
        git add timeseries.png  # Ensure this matches the saved plot file name
        git add map.png
        
        # Check if there are changes to commit
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Update plots"
        fi
        
        # Push the changes
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
