name: manual

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.11'
        activate-environment: test

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Print working directory
      run: pwd

    - name: Run lightning_timeseries.py
      run: 
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate test
        python lightning_timeseries.py
        echo $PATH
      shell: bash

    -  name: Print working directory
       run: pwd

    - name: List files in output directory
      run: ls -R 

    - name: Commit and push output image
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add /home/runner/work/nickmesa.github.io/nickmesa.github.io/figure.png
        git commit -m 'Add output image'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload figure as artifact
      uses: actions/upload-artifact@v3
      with:
        name: figure
        path: /home/runner/work/nickmesa.github.io/nickmesa.github.io/figure.png
