name: manual

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.11'
        activate-environment: test

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Run lightning_timeseries.py
      run: 
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate test
        python .github/workflows/lightning_timeseries.py

    - name: List files in output directory
      run: ls -R Total_Energy_Timeseries_Figs

    - name: Commit and push output image
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add Total_Energy_Timeseries_Figs/total_energy_timeseries.png
        git commit -m 'Add output image'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
