name: Run Script Every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.11'
        
    - name: Create Conda environment
      run: conda env create -f test.yml

    - name: Activate Conda environment
      run: echo "conda activate myenv" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Run lightning_timeseries.py
      run: 
        conda activate myenv
        python lightning_timeseries.py
