name: Create Plot

on:
  workflow_dispatch:

jobs:
  create_plot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the version of Python you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib

    - name: Run plot script
      run: python create_plot.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add plot.png
        git commit -m "Add plot"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
